### PR TITLE
[Chore] remove conference calling flag

### PR DESCRIPTION
**Pull request by David-Henner**
## What's new in this PR?

- Remove the conference calling flag and update calling logic accordingly

### CODE REVIEW

**Review by johnxnguyen — CHANGES_REQUESTED** [review]
Don't forget that the client can still answer legacy calls, so you need to provide update the callsnapshot flag `isConferenceCall` when you answer a call and start a call. This will also affect the `callType` property because if you answer a legacy call you need to adhere to the group video limit. You'll need to assert these in tests too.

Otherwise 👍

**Comment by David-Henner** [comment]
> Don't forget that the client can still answer legacy calls, so you need to provide update the callsnapshot flag `isConferenceCall` when you answer a call and start a call. This will also affect the `callType` property because if you answer a legacy call you need to adhere to the group video limit. You'll need to assert these in tests too.

I understand, but looking at the previous `callType` implementation:

```
    private func callType(for conversation: ZMConversation, startedWithVideo: Bool) -> AVSCallType {
         if !useConferenceCalling && conversation.localParticipants.count > legacyVideoParticipantsLimit {	
             return .audioOnly		
         } else {		
             return startedWithVideo ? .video : .normal		
         }		
     }
```

We see that it checks if `useConferenceCalling` is `false` before looking at the legacy call limit.

That flag was always set on the client side only, so if an incoming call was using legacy but the client enabled conference calling, we would still answer with either `.video` or `.normal`. Only when starting a call we would use `.audioOnly` if conference calling wasn't enabled.

Now, `useConferenceCalling` is always true and, in the future, removing the `if - else` statement shouldn't alter behaviour.

However, If it's necessary to answer an incoming legacy call with `.audioOnly`, I think we could look at the incoming call snapshot to determine the type of call.

**Comment by johnxnguyen** [comment]
> N

@David-Henner yes I know, I think that was a mistake in our initial implementation. Perhaps it's worth checking with product to be sure that we need to consider limits for legacy calls we answer. If not, then I guess we have no need to distinguish between legacy and conference calls now? Otherwise we should still retain the information that the incoming call is not a conference call.

**Comment by David-Henner** [comment]
- Updated `callType` to take into account incoming legacy calls.
- Updated tests to test for legacy and conference calling

**Review by johnxnguyen — APPROVED** [review]

**Review by KaterinaWire — APPROVED** [review]

**Comment by David-Henner** [comment]
@zenkins release major

**Pull request merged**
