### PR TITLE
Remove Clusterizer class

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* This class has been moved to `wire-ios-data-model` in https://github.com/wireapp/wire-ios-data-model/pull/243.

### This PR depends on:
- [x] A new release of `wire-ios-data-model` after https://github.com/wireapp/wire-ios-data-model/pull/243 has been merged.

### CODE REVIEW

**Comment by typfel** [comment]
Is the clusterizer public API?

**Comment by daehn** [comment]
@typfel Yes

**Comment by typfel** [comment]
@daehn  so an API breaker then? :)

**Comment by daehn** [comment]
@typfel but I don't think it's used in the UI project (yet), but always safer to make this a major.

**Comment by daehn** [comment]
@typfel let's wait for Circle

**Pull request merged**
