### PR TITLE
Integrate SwiftLint into the iOS Sync Engine Project

### PR DESCRIPTION
**Pull request by agisilaos**
## What's new in this PR?

Integrating SwiftLint into the iOS Sync Engine project. The .swiftlint.yml file is based on the file that's been added on the wire-ios repository. I've also added a GitHub action for SwiftLint

## Notes

https://wearezeta.atlassian.net/jira/software/projects/IC/boards/100?selectedIssue=IC-6

### CODE REVIEW

**Comment by billypchan** [comment]
we should find a way to skip untouched files in this PR?

**Review by billypchan — COMMENTED** [review]
prevent error and just leave warnings

**Comment by agisilaos** [comment]
> we should find a way to skip untouched files in this PR?

What do you mean? @billypchan

**Comment by billypchan** [comment]
I found the new section below, will it appear in every PR if this PR is merged?
Screenshot 2021-11-08 at 08 44 45

**Comment by agisilaos** [comment]
Not sure.

**Comment by agisilaos** [comment]
I believe this is good to go for review. I addressed @billypchan's comments.

**Review by sb88k — APPROVED** [review]

**Review by billypchan — APPROVED** [review]

**Pull request merged**
