### PR TITLE
Remove APNS performance tracking, add pingback logs

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* Adds a missing `isEqual` implementation to `EventsWithIdentifier`.
* Remove classes and logic used to track APNS performance.
* Add more logs to the `BackgroundAPNSPingbackStatus` with the tag `"Pingback"` in order to see when and which notification IDs are added to the list of Ids to be fetched. This will be used to debug request loops to the `/notifications` endpoint and will be enabled for internal build by default in https://github.com/wireapp/wire-ios/pull/980.

### CODE REVIEW

**Comment by daehn** [comment]
@typfel please re-review, a missing `isEqual` implementation was added in dec5a0c as well.

**Comment by typfel** [comment]
Is adding the missing isEqual implementation fixing a bug? Should we maybe have a test for it.

**Comment by vytis** [comment]
@typfel adding some tests for it

**Comment by daehn** [comment]
It's a case of "How did this ever work", as we are comparing two objects of this type in multiple places…

**Comment by daehn** [comment]
@typfel @mikeger please re-review, would be good to get this into internal fast to get more meaningful logs.

**Pull request merged**
