### PR TITLE
Move isGroup and isConstantBitRate into CallSnapshot

### PR DESCRIPTION
**Pull request by typfel**
## What's new in this PR?

Move some state properties into the `CallSnapshot`: `isGroup` and `isConstantBitRate`. This simplifies the interface and makes sure we don't keep any state around after the call is over.

### CODE REVIEW

**Comment by mikeger** [comment]
@typfel should be merged? Or some things to fix in the tests?

**Comment by typfel** [comment]
@mikeger I'll need to check the tests. This is not urgent it's not a fix for anything.

**Comment by mikeger** [comment]
Sure, just afraid that we'll have to merge it later, but in fact there is no hurry.

**Comment by mikeger** [comment]
@typfel ;)

**Comment by typfel** [comment]
@mikeger yes, let me update the tests :)

**Comment by typfel** [comment]
@mikeger ok finally updated this :)

**Pull request merged**
