### PR TITLE
chore: improve call closed reason mapping SQCALL-493

### PR DESCRIPTION
**Pull request by David-Henner**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCALL-493" title="SQCALL-493" target="_blank">TaskSQCALL-493</a>  [iOS] Improve AVS call_reason mapping in clients
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some of the call end reasons provided by AVS are not mapped properly in the clients

### Solutions

Add missing cases to the `CallClosedReason` enum

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by agisilaos — APPROVED** [review]

**Review by KaterinaWire — APPROVED** [review]

**Comment by David-Henner** [comment]
release major

**Comment by zenkins** [comment]
Hello, @David-Henner! Merging PR for command **release major** for PR #**1674**. Will create a **major** release after merged.
Next version is 413.0.0.

**Comment by David-Henner** [comment]
release major

**Comment by zenkins** [comment]
Hello, @David-Henner! Merging PR for command **release major** for PR #**1674**. Will create a **major** release after merged.
Next version is 413.0.0.

**Pull request merged**
