### PR TITLE
feat: Add new error code for ConversationJoinError enum SQSERVICES-1276

### PR DESCRIPTION
**Pull request by KaterinaWire**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1276" title="SQSERVICES-1276" target="_blank">StorySQSERVICES-1276</a>  [iOS] warn about disabled guest links
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

We need to handle an error code when someone wants to join a conversation with a guest link, but guest link has been disabled at the same time.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by agisilaos — APPROVED** [review]

**Comment by agisilaos** [comment]
@KaterinaWire Do we have a test for this new error that we're introducing? I think other cases are covered in `ConversationTests_Join` but not that one.

**Comment by KaterinaWire** [comment]
> @KaterinaWire Do we have a test for this new error that we're introducing? I think other cases are covered in `ConversationTests_Join` but not that one. Also can you please take care of the SwiftLint warning?

@agisilaos  But the SwiftLint warning wasn't introduced by my changes. Have we recently added new rules?

**Comment by agisilaos** [comment]
> > @KaterinaWire Do we have a test for this new error that we're introducing? I think other cases are covered in `ConversationTests_Join` but not that one. Also can you please take care of the SwiftLint warning?
> 
> @agisilaos But the SwiftLint warning wasn't introduced by my changes. Have we recently added new rules?

Nope we didn't introduce any new rules. Like I mentioned in another PR. I'm planning to introduce a new SwiftLint file soonish where it's going to be named autocorrect-swiftlint and the rules on that file are going to be fixed automatically when we're building the project. 

Until then we need to be a tad careful and not let those warnings slip up from the review.

**Review by johnxnguyen — APPROVED** [review]

**Comment by KaterinaWire** [comment]
release minor

**Comment by KaterinaWire** [comment]
release minor

**Comment by KaterinaWire** [comment]
release minor

**Comment by zenkins** [comment]
Hello, @KaterinaWire! Merging PR for command **release minor** for PR #**1673**. Will create a **minor** release after merged.
Next version is 412.4.0.

**Pull request merged**
