### PR TITLE
fix: fetch all missing profile images SQCORE-1226

### PR DESCRIPTION
**Pull request by johnxnguyen**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1226" title="SQCORE-1226" target="_blank">BugSQCORE-1226</a>  [iOS] Profile images can't be downloaded on staging backend
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some profile images are missing.

### Causes (Optional)

There was an issue where profile images couldn't be fetched. This was solved in https://github.com/wireapp/wire-ios-transport/pull/238. While we can now fetch profile images again, they're not all loaded because each user needs to be refetched, which doesn't happen all at once without some kind of forced synchronisation with the backend.

### Solutions

Force sync all users to fetch their profile images.

### Testing

Added a test for the hot fix patch.

### Notes

This issues is most noticeable when upgrading from a version without the fix in https://github.com/wireapp/wire-ios-transport/pull/238 to a version that does.

When freshly installing the app, we always perform an initial sync with the backend, so in this case we see all the profile images.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by KaterinaWire** [comment]
@johnxnguyen Should we also change `MAJOR_VERSION` and `CURRENT_PROJECT_VERSION` ?

**Comment by johnxnguyen** [comment]
@KaterinaWire it should happen when the framework is released.

**Review by David-Henner — APPROVED** [review]

**Review by KaterinaWire — APPROVED** [review]

**Comment by David-Henner** [comment]
release patch

**Comment by zenkins** [comment]
Hello, @David-Henner! Merging PR for command **release patch** for PR #**1660**. Will create a **patch** release after merged.
Next version is 412.3.3.

**Pull request merged**
