### PR TITLE
Remove user image for account with team

### PR DESCRIPTION
**Pull request by mikeger**
- Not sure how the issue could happen, but for me the team account after some time got the image set, this should forbid it.

### CODE REVIEW

**Comment by typfel** [comment]
Maybe because we sync the self user and picture before the team?

**Comment by mikeger** [comment]
@typfel this could be the case, then I guess I can check the team_id on self user.

**Comment by mikeger** [comment]
@typfel we don't have the team id property any more, so I think checking if the team relation is there via `isTeamMember` is correct way to do it.

**Comment by typfel** [comment]
Does that membership get created when the self user is synced? Didn't look like it in`updateWithTransportData:` in data model because then it as the same behaviour has before.

**Comment by mikeger** [comment]
I checked now and we first fetch /self, then /teams, so it can happen that user has no team for some time, then this fix makes sense.

**Pull request merged**
