### PR TITLE
Feature/block suspended account

### PR DESCRIPTION
**Pull request by johnxnguyen**
When attempting to sign in with a *suspended* account, backend will return the error code `403` with  label `suspended`. This PR adds the new error type and checks for it in the request response and sends the appropriate notification.

### CODE REVIEW

**Comment by typfel** [comment]
Conflict!

🔥 🔥 🔥🚒 🚒 🚒

**Comment by typfel** [comment]
@johnxnguyen a test perhaps in `LoginTranscoderTests`

**Comment by johnxnguyen** [comment]
@typfel yeah I was just thinking about that. We need to make the account suspended, that would require changes to `MockTransport`?

**Comment by typfel** [comment]
No not necessary these are not integration tests.

**Pull request merged**
