### PR TITLE
refactor: notification service extension SERVICES-1107

### PR DESCRIPTION
**Pull request by KaterinaWire**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SERVICES-1107" title="SERVICES-1107" target="_blank">EpicSERVICES-1107</a>  Notification Service Extension
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Notification service extension implementation.

Needs releases with:

- https://github.com/wireapp/wire-ios-request-strategy/pull/313
- https://github.com/wireapp/wire-ios-data-model/pull/1026
- https://github.com/wireapp/wire-ios-mocktransport/pull/223
- https://github.com/wireapp/wire-ios-transport/pull/243
- https://github.com/wireapp/wire-ios-utilities/pull/136

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by johnxnguyen — APPROVED** [review]

**Review by agisilaos — APPROVED** [review]
We have some SwiftLint warnings that we need to take care of. Can we please fix them before merging?

**Comment by KaterinaWire** [comment]
> We have some SwiftLint warnings that we need to take care of. Can we please fix them before merging?

@agisilaos  Fixed

**Comment by johnxnguyen** [comment]
release major

**Comment by zenkins** [comment]
Hello, @johnxnguyen! Merging PR for command **release major** for PR #**1620**. Will create a **major** release after merged.
Next version is 414.0.0.

**Pull request merged**
