### PR TITLE
Allow storing data container in app data

### PR DESCRIPTION
**Pull request by mikeger**
Requires https://github.com/wireapp/wire-ios-data-model/pull/43

# Issue

On Travis there is no signing identity, and Xcode forbids using the shared container for our app during the tests, this makes tests crash. This is also the issue for external people who have no signing identity.

# Solution

Solution is to allow storing database in Application Data for simulator and builds that are non enterprise and non-appstore.

### CODE REVIEW

**Comment by daehn** [comment]
The `EventDecoder` also needs the shared container to create it`s database

**Comment by mikeger** [comment]
@daehn updated

**Comment by marcoconti83** [comment]
Do not merge yet, waiting for @daehn fix on ZIOS-7259 to make a release with just that

**Comment by marcoconti83** [comment]
What's the status of this?

**Comment by mikeger** [comment]
@marcoconti83 it "Requires wireapp/wire-ios-data-model#43"

**Comment by marcoconti83** [comment]
Data model released as 17.0.4

**Comment by marcoconti83** [comment]
Now it has conflicts 👎

**Comment by mikeger** [comment]
@marcoconti83 fixed

**Pull request merged**
