### PR TITLE
Wait longer for xcodebuild

### PR DESCRIPTION
**Pull request by daehn**

### CODE REVIEW

**Comment by marcoconti83** [comment]
On our junkins machine, it might take longer than 30 minutes. Maybe we should bump it to 45?

**Comment by daehn** [comment]
@marcoconti83 travis timed out even with 90 min 😁...

**Comment by marcoconti83** [comment]
@daehn I think the issue might be somewhere else then. Probably the simulator is stuck on the host machine. One idea would be to look at the travis configuration for any other frameworks currently working fine with travis that has a test host app (some of them don't) and see if we spot any difference.

**Comment by daehn** [comment]
`wire-ios-link-preview` also has a test host app, but the install and test commands in the `.travis.yml` are not really different there

**Pull request closed without merging**
